AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'mitamae/plugins/**/*'

Metrics/LineLength:
  Enabled: false

# No mruby support
Performance/StringReplacement:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false

Style/Documentation:
  Enabled: false
