- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64
    dest: "{{ ansible_env.HOME }}/.local/bin/docker-compose"
    sha256sum: 8d55adce12461c9f2abd907da1138b3e925919212611a54c94c4794ab0a975fc
    mode: 0755

- name: Add user to docker group
  user:
    append: yes
    name: moe
    groups: docker
  become: yes
