- name: Install wego
  shell: go get -u github.com/schachmat/wego
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.GOPATH }}/bin/wego"

- name: Install geodig
  shell: go get -u github.com/dutchcoders/geodig
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.GOPATH }}/bin/geodig"

- name: Install embedmd
  shell: go get -u github.com/campoy/embedmd
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.GOPATH }}/bin/embedmd"

- name: Install lego
  shell: go get -u github.com/xenolf/lego
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.GOPATH }}/bin/lego"
