---
- set_fact:
    terraform_version: 0.9.8
    vault_version: 0.7.0
    vagrant_version: 1.9.3
    packer_version: 1.0.0
    bin_path: "{{ ansible_env.HOME }}/.local/bin"

- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: "{{ bin_path }}"
    remote_src: True

- name: Install Vault
  unarchive:
    src: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
    dest: "{{ bin_path }}"
    remote_src: True

- name: Install Packer
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: "{{ bin_path }}"
    remote_src: True

- name: Install Vagrant
  apt: deb=https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
  become: yes
