---
- name: repos
  hosts: 127.0.0.1
  vars_files:
    - "vars/common.yml"
  roles:
    - repos

- name: packages
  hosts: 127.0.0.1
  vars_files:
    - "vars/common.yml"
  roles:
    - packages

- name: fonts
  hosts: 127.0.0.1
  vars_files:
    - "vars/common.yml"
  roles:
    - fonts

- name: certificates
  hosts: 127.0.0.1
  roles:
    - certificates

- name: configuration
  hosts: 127.0.0.1
  roles:
    - configuration
